#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define TAILLE_BLOCS                34
#define NB_BLOCS_LARGEUR            13
#define NB_BLOCS_HAUTEUR            15
#define TAILLE_FENETRE_LARGEUR      TAILLE_BLOCS * NB_BLOCS_LARGEUR
#define TAILLE_FENETRE_HAUTEUR      TAILLE_BLOCS * NB_BLOCS_HAUTEUR
#define TAILLE_FENETRE_HAUTEUR_TOT  TAILLE_BLOCS * NB_BLOCS_HAUTEUR + 200
#define TAILLE_FENETRE_LARGEUR_TOT  TAILLE_BLOCS * NB_BLOCS_LARGEUR + 200

typedef enum Bloc Bloc;
enum Bloc
{
    JAUNE,BLEU,ROUGE,VERT,VIOLET,BOMBE,VIDE
};

enum{GAUCHE, DROITE};

#endif // CONSTANTES_H_INCLUDED
